export const ACTIONS = {
	BOOK_CREATE_OR_UPDATE: 'ACTION_BOOK_CREATE_OR_UPDATE',
	BOOK_DELETE: 'ACTION_BOOK_DELETE'
}

export const MUTATIONS = {
	BOOK_CREATE_OR_UPDATE: 'MUTATION_BOOK_CREATE_OR_UPDATE',
	BOOK_DELETE: 'MUTATION_BOOK_DELETE'
}